# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ids2xyz <- function(IDS, DIMS) {
    .Call(`_ARIbrain_ids2xyz`, IDS, DIMS)
}

findAdjList <- function(MASK, INDEXP, DIMS, m, conn) {
    .Call(`_ARIbrain_findAdjList`, MASK, INDEXP, DIMS, m, conn)
}

findClusters <- function(m, ADJ, ORD, RANK) {
    .Call(`_ARIbrain_findClusters`, m, ADJ, ORD, RANK)
}

forestTDP <- function(m, h, alpha, simesh, P, ORD, SIZE, ROOT, CHILD) {
    .Call(`_ARIbrain_forestTDP`, m, h, alpha, simesh, P, ORD, SIZE, ROOT, CHILD)
}

queryPreparation <- function(m, ROOT, TDP, CHILD) {
    .Call(`_ARIbrain_queryPreparation`, m, ROOT, TDP, CHILD)
}

answerQuery <- function(gamma, ADMSTC, ORD, SIZE, MARK, TDP, CHILD) {
    .Call(`_ARIbrain_answerQuery`, gamma, ADMSTC, ORD, SIZE, MARK, TDP, CHILD)
}

counting_sort <- function(n, maxid, CLSTRSIZE) {
    .Call(`_ARIbrain_counting_sort`, n, maxid, CLSTRSIZE)
}

findalpha <- function(p, m, simesfactor, simes) {
    .Call(`_ARIbrain_findalpha`, p, m, simesfactor, simes)
}

findsimesfactor <- function(simes, m) {
    .Call(`_ARIbrain_findsimesfactor`, simes, m)
}

adjustedElementary <- function(p, alpha, m, simesfactor) {
    .Call(`_ARIbrain_adjustedElementary`, p, alpha, m, simesfactor)
}

adjustedIntersection <- function(pI, alpha, m, simesfactor) {
    .Call(`_ARIbrain_adjustedIntersection`, pI, alpha, m, simesfactor)
}

findHalpha <- function(jumpalpha, alpha, m) {
    .Call(`_ARIbrain_findHalpha`, jumpalpha, alpha, m)
}

findConcentration <- function(p, simesfactor, h, alpha, m) {
    .Call(`_ARIbrain_findConcentration`, p, simesfactor, h, alpha, m)
}

findDiscoveries <- function(idx, allp, simesfactor, h, alpha, k, m) {
    .Call(`_ARIbrain_findDiscoveries`, idx, allp, simesfactor, h, alpha, k, m)
}

