# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findClusters <- function(MASK, INDEXP, DIMS, SIZE, ROOT, m, conn) {
    .Call('_ARIbrain_findClusters', PACKAGE = 'ARIbrain', MASK, INDEXP, DIMS, SIZE, ROOT, m, conn)
}

forestTDP <- function(m, h, alpha, simesh, P, SIZE, ROOT, CHILD) {
    .Call('_ARIbrain_forestTDP', PACKAGE = 'ARIbrain', m, h, alpha, simesh, P, SIZE, ROOT, CHILD)
}

queryPreparation <- function(m, ROOT, TDP, CHILD) {
    .Call('_ARIbrain_queryPreparation', PACKAGE = 'ARIbrain', m, ROOT, TDP, CHILD)
}

answerQuery <- function(m, g, L, SIZE, TDP, CHILD) {
    .Call('_ARIbrain_answerQuery', PACKAGE = 'ARIbrain', m, g, L, SIZE, TDP, CHILD)
}

findalpha <- function(p, m, simesfactor, simes) {
    .Call('_ARIbrain_findalpha', PACKAGE = 'ARIbrain', p, m, simesfactor, simes)
}

findsimesfactor <- function(simes, m) {
    .Call('_ARIbrain_findsimesfactor', PACKAGE = 'ARIbrain', simes, m)
}

adjustedElementary <- function(p, alpha, m, simesfactor) {
    .Call('_ARIbrain_adjustedElementary', PACKAGE = 'ARIbrain', p, alpha, m, simesfactor)
}

adjustedIntersection <- function(pI, alpha, m, simesfactor) {
    .Call('_ARIbrain_adjustedIntersection', PACKAGE = 'ARIbrain', pI, alpha, m, simesfactor)
}

findHalpha <- function(jumpalpha, alpha, m) {
    .Call('_ARIbrain_findHalpha', PACKAGE = 'ARIbrain', jumpalpha, alpha, m)
}

findConcentration <- function(p, simesfactor, h, alpha, m) {
    .Call('_ARIbrain_findConcentration', PACKAGE = 'ARIbrain', p, simesfactor, h, alpha, m)
}

findDiscoveries <- function(idx, allp, simesfactor, h, alpha, k, m) {
    .Call('_ARIbrain_findDiscoveries', PACKAGE = 'ARIbrain', idx, allp, simesfactor, h, alpha, k, m)
}

