# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findClusters <- function(MASK, INDEXP, DIMS, SIZE, ROOT, m, conn) {
    .Call(`_ARIbrain_findClusters`, MASK, INDEXP, DIMS, SIZE, ROOT, m, conn)
}

forestTDP <- function(m, h, alpha, simesh, P, SIZE, ROOT, CHILD) {
    .Call(`_ARIbrain_forestTDP`, m, h, alpha, simesh, P, SIZE, ROOT, CHILD)
}

queryPreparation <- function(m, ROOT, TDP, CHILD) {
    .Call(`_ARIbrain_queryPreparation`, m, ROOT, TDP, CHILD)
}

answerQuery <- function(m, g, L, SIZE, TDP, CHILD) {
    .Call(`_ARIbrain_answerQuery`, m, g, L, SIZE, TDP, CHILD)
}

findalpha <- function(p, m, simesfactor, simes) {
    .Call(`_ARIbrain_findalpha`, p, m, simesfactor, simes)
}

findsimesfactor <- function(simes, m) {
    .Call(`_ARIbrain_findsimesfactor`, simes, m)
}

adjustedElementary <- function(p, alpha, m, simesfactor) {
    .Call(`_ARIbrain_adjustedElementary`, p, alpha, m, simesfactor)
}

adjustedIntersection <- function(pI, alpha, m, simesfactor) {
    .Call(`_ARIbrain_adjustedIntersection`, pI, alpha, m, simesfactor)
}

findHalpha <- function(jumpalpha, alpha, m) {
    .Call(`_ARIbrain_findHalpha`, jumpalpha, alpha, m)
}

findConcentration <- function(p, simesfactor, h, alpha, m) {
    .Call(`_ARIbrain_findConcentration`, p, simesfactor, h, alpha, m)
}

findDiscoveries <- function(idx, allp, simesfactor, h, alpha, k, m) {
    .Call(`_ARIbrain_findDiscoveries`, idx, allp, simesfactor, h, alpha, k, m)
}

